site_name: Заметки
dev_addr: 127.0.0.1:9000
nav:
    - Начало: index.md
    - Linux: linux.md
    - Bush: bash.md
    - Разработка: devel.md
    - Ассемблер: asm.md
    - Андроид: android.md
    - Баги: bugs.md
    - Поиск багов: hack.md
    - Безопасность: secur.md
    - Документация: docs.md
    - Железо: hard.md
    - Картинки: pics.md
    - Популярная наука: pop_sciense.md
    - Работа: work.md
    - Шахматы: chess.md
    - Юмор: humor.md
    - Windows: windows.md
    - Разработка Windows: windows_devel.md
    - Домовой: house_keeper.md

theme:
  custom_dir: 'theme'
  name: 'material'
  language: 'ru'
  palette:
    primary: 'blue grey'
    accent: 'purple'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: '/images/baseline-bookmark_border-24px.svg'
  favicon: '/images/baseline-bookmark_border-24px.svg'
